### ISSUE TITLE
.text section is too large (> 1024 bytes)

### ISSUE THREAD

**Issue by Merok** [IAIK/coco-alma#4]
Hi,

I am trying to experiment with your verification tool as I find it very interesting.
I work on "Rocky Linux "8.4 (Green Obsidian). I had issues with the `pip install python-sat==0.1.7.dev10`
so I installed python-sat using `pip install python-sat[pblib,aiger]` (maybe this might create error later on ?).

I am following the steps mentioned in https://github.com/IAIK/coco-alma/tree/master/examples/ibex.
Unfortunately, I am stuck at the section "Compile RISC-V Program and create the header for the testbench".
When I run: 
`assemble.py --program programs/aes_sbox.S --netlist ../../tmp/circuit.v`

I obtain:
```
Using program file:  programs/aes_sbox.S
Using initialization file:  None
Using build directory: /volume1/scratch/jgaspoz/cocoAlma/coco-alma/tmp
Using netlist path: ../../tmp/circuit.v

.text section is too large (> 1024 bytes)
```

Do you know how to fix this error ?

Thanks a lot for you help.

**Comment by barbara-gigerl** [comment]
Hi,
the basic version of ibex, as you can find it in the repo, is equipped with 1024 bytes of ROM (https://github.com/IAIK/coco-ibex/blob/master/shared/rtl/rom_1p.v) - if you need more, just change the `Depth` parameter and synthesize ibex again.

**Comment by Merok** [comment]
Hi,

Thanks for the fast answer.
I changed the original value of `localparam Depth = 256` to 1024 and managed to run the assemble.py script. 
I am a bit confused now how to label the registers and memory correctly according to the aes_sbox.S program.

Thanks again for your help.

**Comment by barbara-gigerl** [comment]
You need to do the annotation in `tmp/labels.txt` (will be generated during parsing).
The general memory layout for shares in the AES test case looks like this:
![aes_mem_labels](https://user-images.githubusercontent.com/10631493/136335328-04147e85-bd1a-4071-ad31-27d625be9c7c.png)
Addionally, everything in memory from 0x160 to 0x1e4 has to be labeled as "mask".
Keep in mind that the labeling is done on bit granularity.
I hope that helps!

**Comment by Merok** [comment]
Thank you for your reply.
Sorry, I am still a bit confused how to label this file. I went back to original `localparam Depth = 256` and tested with the stable_fail_4.s program but the labels.txt file is very large. I am not sure how to map register used from the .S program to the labels.txt file and correctly annotate the file.

Would you have some simple example at disposition ?
Thanks again for your help.

**Comment by vedadux** [comment]
We have noticed the labeling problem as well: there is just too much information in the labels.txt file. On the "hw-verif" branch, that problem has been solved and we have much more user-friendly labeling files, where you can just write down the memory locations or ports you are interested in. However, that branch is mostly meant for hardware masking verification and is not merged as of now.

Maybe you can try out the Prince-TI or AES-DOM examples as a starting point in that direction.

**Comment by vedadux** [comment]
Now that I think about it, it would make sense to add some automatic labeling script for the provided testcases. When writing the paper we had some internal ones, I think, so that should not be hard. Can you add them @barbara-gigerl ?

**Comment by vedadux** [comment]
@Merok Regarding your actual question:

You have to label all memory bits from 352 to 484 as masks like this:
```
u_ram.mem[352]:0:some_number: mask
u_ram.mem[352]:1:some_number: mask
...
u_ram.mem[484]:30:some_number: mask
u_ram.mem[484]:31:some_number: mask
```
and do the same for the memory regions of the secrets:
```
u_ram.mem[0]:0:some_number: share 1
u_ram.mem[4]:0:some_number: share 1
...
u_ram.mem[56]:0:some_number: share 8
u_ram.mem[60]:0:some_number: share 8
```

I am not sure if this is the exact mapping but it should give you the gist.

**Comment by Merok** [comment]
Thanks for the reply @vedadux. I will try to fill the labels.txt file according to your suggestions.
Indeed, making the labelling automatic would greatly ease this task.

Thanks
