### ISSUE TITLE
trace.py errors

### ISSUE THREAD

**Issue by Merok** [IAIK/coco-alma#5]
Hello,

I am trying to run the example provided in your github (using the stable_ok_10.S program). When running the trace.py script, the execution stops due to errors (in the "3: Compiling provided verilator testbench" stage):

> clang-12: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
> In file included from tmp/verilator_tb.c:3:
> 
> tmp/ram_init.h:2:15: error: no member named 'ibex_top__DOT__instr_rom__02emem__05b0__05d' in 'Vcircuit'; did you mean 'ibex_top__DOT__instr_rom__02Emem__05B0__05D'?
>   tb->m_core->ibex_top__DOT__instr_rom__02emem__05b0__05d = 0x00000000;
>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>               ibex_top__DOT__instr_rom__02Emem__05B0__05D
> coco-alma/tmp/obj_dir/Vcircuit.h:22137:27: note: 'ibex_top__DOT__instr_rom__02Emem__05B0__05D' declared here
>             IData/*31:0*/ ibex_top__DOT__instr_rom__02Emem__05B0__05D;
>                           ^
> In file included from tmp/verilator_tb.c:3:
> tmp/ram_init.h:3:15: error: no member named 'ibex_top__DOT__instr_rom__02emem__05b1__05d' in 'Vcircuit'; did you mean 'ibex_top__DOT__instr_rom__02Emem__05B1__05D'?
>   tb->m_core->ibex_top__DOT__instr_rom__02emem__05b1__05d = 0x00000000;
>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>               ibex_top__DOT__instr_rom__02Emem__05B1__05D
> coco-alma/tmp/obj_dir/Vcircuit.h:22252:27: note: 'ibex_top__DOT__instr_rom__02Emem__05B1__05D' declared here
>             IData/*31:0*/ ibex_top__DOT__instr_rom__02Emem__05B1__05D;
>                           ^
> In file included from tmp/verilator_tb.c:3:
> tmp/ram_init.h:4:15: error: no member named 'ibex_top__DOT__instr_rom__02emem__05b2__05d' in 'Vcircuit'; did you mean 'ibex_top__DOT__instr_rom__02Emem__05B2__05D'?
>   tb->m_core->ibex_top__DOT__instr_rom__02emem__05b2__05d = 0x00000000;
>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>               ibex_top__DOT__instr_rom__02Emem__05B2__05D
> coco-alma/tmp/obj_dir/Vcircuit.h:22321:27: note: 'ibex_top__DOT__instr_rom__02Emem__05B2__05D' declared here
>             IData/*31:0*/ ibex_top__DOT__instr_rom__02Emem__05B2__05D;
>                           ^
> ...
>                           
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.

Do you have an idea why I obtain such errors ?
Thank you for your help.

Best

**Comment by vedadux** [comment]
Hi @Merok,

this appears to be a discrepancy in the way Verilator names the variables it generates. This can be seen in these lines:
```
In file included from tmp/verilator_tb.c:3:
tmp/ram_init.h:3:15: error: no member named 'ibex_top__DOT__instr_rom__02emem__05b1__05d' in 'Vcircuit'; did you mean 'ibex_top__DOT__instr_rom__02Emem__05B1__05D'?
```
I think this is due to the Verilator version and needs to be adjusted accordingly, either by the user, or we need to do some version detection for Verilator which sounds painful. I have added the option `--uppercase` to the assembler that should fix your issue. 

Best regards

**Comment by barbara-gigerl** [comment]
Hi,
for me it looks like your instruction ROM is not big enough to hold your program.
Follow the instructions there: https://github.com/IAIK/coco-alma/issues/4#issuecomment-936189361
Best regards

**Comment by Merok** [comment]
Thanks for the replies.
I have updated the ROM size to 1024 and used the --uppercase option which made it work.
However now the verify.py script does not work (I am testing for the aes_Sbox.S program).
Here is my error:

> | CircuitGraph | Total: 158177 | Linear: 1139 | Non-linear: 36132 | Registers: 39491 | Mux: 74738 | 
tmp/circuit.vcd:49555: [WARNING] Entry for name clk_sys already exists in namemap (clk_sys -> 3.A)
tmp/circuit.vcd:49565: [WARNING] Entry for name instr_be already exists in namemap (instr_be -> ;.A)
tmp/circuit.vcd:50606: [WARNING] Entry for name instr_wdata already exists in namemap (instr_wdata -> C.A)
tmp/circuit.vcd:50607: [WARNING] Entry for name instr_we already exists in namemap (instr_we -> K.A)
tmp/circuit.vcd:50608: [WARNING] Entry for name rst_sys_n already exists in namemap (rst_sys_n -> S.A)
Traceback (most recent call last):
  File "verify.py", line 203, in <module>
    main()
  File "verify.py", line 182, in main
    status, locations = checker.check()
  File "coco-alma/SatChecker.py", line 854, in check
    leaks = self.__check_secure_once()
  File "coco-alma/SatChecker.py", line 815, in __check_secure_once
    self.__find_reset(self.rst_phase)
  File "coco-alma/SatChecker.py", line 491, in __find_reset
    assert(self.trace.get_signal_value(self.rst_name, 0) == reset), "reset duration mismatch"
AssertionError: reset duration mismatch

Any idea of why I have this error ?

Thanks again for the help.

Best

**Comment by vedadux** [comment]
The error message should give you an idea. The reset duration does not match the one used in the testbench. This is due to a mistake in the readme.md file. Please try it again with `--rst-cycles 2` instead.
